/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useTexture } from '@react-three/drei'

export default function Skull(props) {
  const group = useRef()
  const texture = useTexture('/SurfaceImperfections003_1K_var1.jpg')
  const { nodes, materials } = useGLTF('/asset_skull.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.SKULL.geometry}
        material={nodes.SKULL.material}
        rotation={[0, 0, 0]}
        scale={[0.18, 0.18, 0.18]}>
        <meshPhysicalMaterial
          envMapIntensity={0.1}
          map={texture}
          clearcoat={0.9}
          clearcoatRoughness={0}
          roughness={0}
          metalness={1}
        />
      </mesh>
    </group>
  )
}

useGLTF.preload('/asset_skull.gltf')
